# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CryptoMonkey_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 540)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ListView_listCriptoCoin = QtWidgets.QListView(self.centralwidget)
        self.ListView_listCriptoCoin.setEnabled(False)
        self.ListView_listCriptoCoin.setGeometry(QtCore.QRect(200, 100, 481, 241))
        self.ListView_listCriptoCoin.setObjectName("ListView_listCriptoCoin")
        self.textEdit_searchCriptoCoin = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_searchCriptoCoin.setGeometry(QtCore.QRect(390, 60, 161, 31))
        self.textEdit_searchCriptoCoin.setMidLineWidth(1)
        self.textEdit_searchCriptoCoin.setObjectName("textEdit_searchCriptoCoin")
        self.pushButton_searchCriptoCoin = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_searchCriptoCoin.setGeometry(QtCore.QRect(560, 60, 113, 32))
        self.pushButton_searchCriptoCoin.setObjectName("pushButton_searchCriptoCoin")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(540, 350, 113, 32))
        self.pushButton.setStatusTip("")
        self.pushButton.setAutoRepeatDelay(280)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(60, 360, 113, 81))
        self.pushButton_2.setObjectName("pushButton_2")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(30, 50, 161, 191))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.comboBox_ExchangeSelection = QtWidgets.QComboBox(self.widget)
        self.comboBox_ExchangeSelection.setEnabled(True)
        self.comboBox_ExchangeSelection.setEditable(True)
        self.comboBox_ExchangeSelection.setCurrentText("")
        self.comboBox_ExchangeSelection.setObjectName("comboBox_ExchangeSelection")
        self.verticalLayout.addWidget(self.comboBox_ExchangeSelection)
        self.pushButton_connectExchange = QtWidgets.QPushButton(self.widget)
        self.pushButton_connectExchange.setObjectName("pushButton_connectExchange")
        self.verticalLayout.addWidget(self.pushButton_connectExchange)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.comboBox_ExchangeSelection.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_searchCriptoCoin.setToolTip(_translate("MainWindow", "<html><head/><body><p>Поиск нужной криптопары</p></body></html>"))
        self.pushButton_searchCriptoCoin.setText(_translate("MainWindow", "Поиск"))
        self.pushButton.setToolTip(_translate("MainWindow", "<html><head/><body><p>Настройка торговли кроптопары</p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "Настройки"))
        self.pushButton_2.setToolTip(_translate("MainWindow", "<html><head/><body><p>Бот начинает торговлю</p></body></html>"))
        self.pushButton_2.setText(_translate("MainWindow", "Start"))
        self.label.setText(_translate("MainWindow", "Выбор биржи"))
        self.pushButton_connectExchange.setToolTip(_translate("MainWindow", "<html><head/><body><p>Получает от биржи торгуемые\n"
"                                    криптопары </p></body></html>\n"
"                                "))
        self.pushButton_connectExchange.setText(_translate("MainWindow", "Подключится"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
