# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Gui_ApiKeysInputWindowSample.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_apiKeysInput(object):
    def setupUi(self, Dialog_apiKeysInput):
        Dialog_apiKeysInput.setObjectName("Dialog_apiKeysInput")
        Dialog_apiKeysInput.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog_apiKeysInput.resize(400, 134)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog_apiKeysInput.sizePolicy().hasHeightForWidth())
        Dialog_apiKeysInput.setSizePolicy(sizePolicy)
        Dialog_apiKeysInput.setMinimumSize(QtCore.QSize(400, 134))
        Dialog_apiKeysInput.setMaximumSize(QtCore.QSize(400, 134))
        Dialog_apiKeysInput.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/Logo.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog_apiKeysInput.setWindowIcon(icon)
        Dialog_apiKeysInput.setWhatsThis("")
        Dialog_apiKeysInput.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0.983, y2:0.227273, stop:0 rgba(227, 91, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        Dialog_apiKeysInput.setModal(True)
        self.pushButton_keysInputEnable = QtWidgets.QPushButton(Dialog_apiKeysInput)
        self.pushButton_keysInputEnable.setGeometry(QtCore.QRect(18, 102, 75, 22))
        self.pushButton_keysInputEnable.setStyleSheet("background-color: rgb(126, 255, 112);")
        self.pushButton_keysInputEnable.setObjectName("pushButton_keysInputEnable")
        self.label_apiKeyInput = QtWidgets.QLabel(Dialog_apiKeysInput)
        self.label_apiKeyInput.setGeometry(QtCore.QRect(298, 48, 47, 13))
        self.label_apiKeyInput.setStyleSheet("background-color: 0,0,0,0")
        self.label_apiKeyInput.setObjectName("label_apiKeyInput")
        self.label_secretKeyInput = QtWidgets.QLabel(Dialog_apiKeysInput)
        self.label_secretKeyInput.setEnabled(True)
        self.label_secretKeyInput.setGeometry(QtCore.QRect(298, 78, 60, 13))
        self.label_secretKeyInput.setAutoFillBackground(False)
        self.label_secretKeyInput.setStyleSheet("background-color: 0,0,0,0")
        self.label_secretKeyInput.setInputMethodHints(QtCore.Qt.ImhNone)
        self.label_secretKeyInput.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_secretKeyInput.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_secretKeyInput.setScaledContents(False)
        self.label_secretKeyInput.setWordWrap(False)
        self.label_secretKeyInput.setIndent(-1)
        self.label_secretKeyInput.setObjectName("label_secretKeyInput")
        self.label_exchangeType = QtWidgets.QLabel(Dialog_apiKeysInput)
        self.label_exchangeType.setEnabled(True)
        self.label_exchangeType.setGeometry(QtCore.QRect(123, 15, 81, 20))
        self.label_exchangeType.setStyleSheet("background-color:0,0,0,10")
        self.label_exchangeType.setAlignment(QtCore.Qt.AlignCenter)
        self.label_exchangeType.setObjectName("label_exchangeType")
        self.comboBox_exchangeType = QtWidgets.QComboBox(Dialog_apiKeysInput)
        self.comboBox_exchangeType.setEnabled(True)
        self.comboBox_exchangeType.setGeometry(QtCore.QRect(18, 14, 100, 22))
        self.comboBox_exchangeType.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox_exchangeType.setObjectName("comboBox_exchangeType")
        self.comboBox_exchangeType.addItem("")
        self.comboBox_exchangeType.addItem("")
        self.comboBox_exchangeType.addItem("")
        self.comboBox_exchangeType.addItem("")
        self.lineEdit_apiKeyInput = QtWidgets.QLineEdit(Dialog_apiKeysInput)
        self.lineEdit_apiKeyInput.setGeometry(QtCore.QRect(18, 43, 271, 24))
        self.lineEdit_apiKeyInput.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_apiKeyInput.setClearButtonEnabled(True)
        self.lineEdit_apiKeyInput.setObjectName("lineEdit_apiKeyInput")
        self.lineEdit_secretKeyInput = QtWidgets.QLineEdit(Dialog_apiKeysInput)
        self.lineEdit_secretKeyInput.setGeometry(QtCore.QRect(18, 72, 271, 24))
        self.lineEdit_secretKeyInput.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_secretKeyInput.setClearButtonEnabled(True)
        self.lineEdit_secretKeyInput.setObjectName("lineEdit_secretKeyInput")

        self.retranslateUi(Dialog_apiKeysInput)
        QtCore.QMetaObject.connectSlotsByName(Dialog_apiKeysInput)

    def retranslateUi(self, Dialog_apiKeysInput):
        _translate = QtCore.QCoreApplication.translate
        Dialog_apiKeysInput.setWindowTitle(_translate("Dialog_apiKeysInput", "Введите ключи для подключения к API аккаунта"))
        self.pushButton_keysInputEnable.setText(_translate("Dialog_apiKeysInput", "Сохранить"))
        self.label_apiKeyInput.setText(_translate("Dialog_apiKeysInput", "API key"))
        self.label_secretKeyInput.setText(_translate("Dialog_apiKeysInput", "Secret key"))
        self.label_exchangeType.setText(_translate("Dialog_apiKeysInput", "Криптобиржа"))
        self.comboBox_exchangeType.setItemText(0, _translate("Dialog_apiKeysInput", "Huobi"))
        self.comboBox_exchangeType.setItemText(1, _translate("Dialog_apiKeysInput", "Myfin"))
        self.comboBox_exchangeType.setItemText(2, _translate("Dialog_apiKeysInput", "Kucoin"))
        self.comboBox_exchangeType.setItemText(3, _translate("Dialog_apiKeysInput", "Coinbase"))
        self.lineEdit_apiKeyInput.setText(_translate("Dialog_apiKeysInput", "Please input api key"))
        self.lineEdit_secretKeyInput.setText(_translate("Dialog_apiKeysInput", "Please input secret key"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_apiKeysInput = QtWidgets.QDialog()
    ui = Ui_Dialog_apiKeysInput()
    ui.setupUi(Dialog_apiKeysInput)
    Dialog_apiKeysInput.show()
    sys.exit(app.exec_())
